version: "3.3"

services:
  web:
    image: ghcr.io/mingj7235/pard-demo/main:latest
    container_name: pard
    environment:
      TZ: "Asia/Seoul"
    networks:
      - bridge
    ports:
      - "8080:8080"

volumes:
  web-server:

networks:
  bridge:
    driver: bridge